// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type LoginUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Otp      string `json:"otp"`
	Token    string `json:"token"`
	Hash     string `json:"hash"`
}

type RegisterUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserResponse struct {
	Name       string `json:"name"`
	Email      string `json:"email"`
	OtpEnabled bool   `json:"otpEnabled"`
	OtpSecret  string `json:"otpSecret"`
	PrivateKey string `json:"privateKey"`
}
